// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QRCODE_API.Inventory;

namespace QRCODE_API.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20210330022032_QrCodeApiMigration")]
    partial class QrCodeApiMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QRCODE_API.Model.CodeSetting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CHG_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CHG_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLASS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CODEDATA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CRT_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CRT_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CUSTOMER_ID")
                        .HasColumnType("int");

                    b.Property<string>("DELETE_YN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ENDDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("LABEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NO")
                        .HasColumnType("int");

                    b.Property<string>("PLACEHOLDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("STARTDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USE_YN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("codesetting");
                });

            modelBuilder.Entity("QRCODE_API.Model.CustomerInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CHG_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CHG_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CRT_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CRT_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUS_ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUS_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUS_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUS_TEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DELETE_YN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EXPIRED_DT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("START_DT")
                        .HasColumnType("datetime2");

                    b.Property<int>("USER_NUM_ALLOW")
                        .HasColumnType("int");

                    b.Property<string>("USE_YN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("customer_info");
                });

            modelBuilder.Entity("QRCODE_API.Model.QrCodeImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CHG_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CHG_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CRT_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CRT_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CUS_ID")
                        .HasColumnType("int");

                    b.Property<string>("DELETE_YN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMAGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USE_YN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("qrcode_image");
                });

            modelBuilder.Entity("QRCODE_API.Model.QrcodeInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BODYTEMPER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("COUNT")
                        .HasColumnType("int");

                    b.Property<int>("CUSTOMER_ID")
                        .HasColumnType("int");

                    b.Property<string>("DATA_INFO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ENDDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ENTRANCETIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("QRCODEYN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("STARTDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("WHERE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WHOM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("qrcode_info");
                });

            modelBuilder.Entity("QRCODE_API.Model.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CHG_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CHG_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CRT_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CRT_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DELETE_YN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROLE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USE_YN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("role");
                });

            modelBuilder.Entity("QRCODE_API.Model.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CHG_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CHG_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CRT_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CRT_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CUSTOMER_ID")
                        .HasColumnType("int");

                    b.Property<string>("DELETE_YN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FULLNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ROLE_ID")
                        .HasColumnType("int");

                    b.Property<string>("USERNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USE_YN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("user");
                });

            modelBuilder.Entity("QRCODE_API.Model.UserLogin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LAST_TIME_LOGIN")
                        .HasColumnType("datetime2");

                    b.Property<string>("LOGIN_YN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("user_login");
                });
#pragma warning restore 612, 618
        }
    }
}
